version: '3'
services:
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  openapi-viewer:
    image: koumoul/openapi-viewer:1
    ports:
      - 5680:8080

  sd:
    image: koumoul/simple-directory:master
    network_mode: host
    environment:
      - ADMINS=["superadmin@test.com","banchereau.tom@gmail.com","alban.mouton@koumoul.com"]
      - PUBLIC_URL=http://localhost:7400/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NUXT_BUILD_BLOCKING=false
      - AUTHRATELIMIT_ATTEMPTS=200
      - DEFAULT_MAX_CREATED_ORGS=10
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

      
volumes:
  mongo-data:
