FROM ghcr.io/koumoul-dev/docker-maplibre-gl-native:master

WORKDIR /webapp

ENV NODE_ENV test

COPY package.json .
COPY package-lock.json .

RUN npm i

RUN mkdir mbtiles
COPY .eslintrc.js .
COPY .gitignore .
COPY public public
COPY server server
COPY test test
COPY config config
COPY scripts scripts
COPY .nycrc .
COPY nuxt.config.js .
COPY contracts contracts
COPY upgrade upgrade


CMD ./node_modules/.bin/nyc xvfb-run -a ./node_modules/.bin/mocha --exit --bail --timeout 20000 test/&& npm run lint
